### ISSUE TITLE
dude are you ok...

### ISSUE THREAD

**Issue by VizzyPop-GH** [DIKnBALZ/inkmix#1]

**Comment by kittstone** [comment]
ive been doing somewhat better since i cancelled inkmix so yeah i guess

**Comment by VizzyPop-GH** [comment]
can you add my new discord account i want to talk and catch up, its me axy.
nexacopic_new is the username

**Comment by kittstone** [comment]
im good, sorry

**Comment by VizzyPop-GH** [comment]
alr, have a good life my guy.
